config/routes.rb
Rails.application.routes.draw do

  #get 'users/new' гет запрос не может создавать ничего, точнее это не правильно
  #get 'users/create'пропишем через ресоурс
#post '/questions', to: 'questions#create'
#patch '/questions/:id', to: 'questions#update'
#delete '/questions/:id', to: 'questions#destroy' єто все заменяется ==> resources :questions
root to: 'questions#index'
resources :questions
resource :session, only: %i[new create destroy]
resources :users, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  #skip_before_action :verify_authenticity_token

before_action :set_question, only: %i[ update show destroy edit]
  def create
  #question = Question.create(
      #body: params[:question][:body],єти два парметра заменяются Хешем с данними
      #user_id: params[:question][:user_id]
      #params[:questions] 2 вариант, он небезопасен
          #)
  #в привате опишем метод  question_params = params.require(:question).permit(:body, :user_id)
    question = Question.create(question_params)

    #flash[:notice] = 'создан'# - можно так

    redirect_to question_path(question), notice: "created neeew"
  end

  def update
    #@question = Question.find(params[:id])
    @question.update(
      body: params[:question][:body],
    user_id: params[:question][:user_id]
       )
          redirect_to question_path(@question), notice: "зберегли ваше питання"
    end

    def destroy
    #  @question = Question.find(params[:id])
      @question.destroy
      redirect_to questions_path, notice: "видалили ваше питання"

    end

    def show
#      @question = Question.find(params[:id])
    end

    def index
      @questions = Question.all
      @question = Question.new
    end

    def new
      @question = Question.new
    end

    def edit
      #@question = Question.find(params[:id]) закинем также в приват
      #redirect_to question_path(@question) после создания гзвфеу перенаправление не надо
    end

    private
      def question_params
         params.require(:question).permit(:body, :user_id)
          end
      def set_question
        @question = Question.find(params[:id])
      end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)
    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])#&. не вдаст ошибки если значение НИЛ
  if user.present?
    session[:user_id] = user.id
  redirect_to root_path, notice: 'You entered on site'
else
  flash.now[:alert] = 'Danger!!!'
  render :new
  end
end

def destroy
session.delete(:user_id)

redirect_to root_path, notice: "Re-Login)))"
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    end

  def create
    user_params = params.require(:user).permit(:name, :nickname, :email, :password)

    User.create(user_params)

    redirect_to root_path, notice: 'Yoo sucefullyy registrated'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11,14)

    case count % 10
  when 1 then one
  when 2..4 then few
  else
    many
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
      <div class="wrapper">
        <div class="navbar">
            <p class="title-sm text-bold"><%= link_to "Ask ME!", root_path%></p>
      <div>
        <% if current_user.present?%>
            <%= content_tag 'span',"@#{current_user.nickname}",class: 'mr-sm'%>
            <%= button_to 'AWAY', session_path, method: :delete %>
               <% else %>
             <%= link_to 'Registration', new_user_path, class: 'button button-yellow mr-sm' %>
            <%= link_to 'Enter', new_session_path, class: 'button button-yellow ' %>
            <% end %>
                  </div>
        </div>

                <% if flash[:notice].present?%>
        <p class="mb mt message message-notice"><%= flash[:notice]%></p>
        <% elsif flash[:alert].present?%>
        <p class="mb mt message message-notice"><%= flash[:alert]%></p>
        <% end %>
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>
<p><%=form.label :body, 'текст вопроса' %></p>
<p><%= form.text_area :body, rows:7, class: "form-text-area" %></p>

<p class="mt"><%= form.label :user_id %></p>
<p><%=form.text_field :user_id, class: "form-text-field" %></p>

<p class="mt"><%=form.submit 'Save', class: "button button-main"%></p>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-sm">
<%= question.body %>
</div>

<div class="text-sm question-footer">
  <div class="text-gray">
      <%= l(question.created_at, format: :short) %>
    </div>

    <div>
      <%=link_to (fa_icon 'pencil'), edit_question_path(question), title: 'изменить вопрос'%>
     <%= button_to (fa_icon 'trash-o'), question_path(question), method: :delete, title: 'Удалить вопрос'%>
    </div>
</div>

app/views/questions/edit.html.erb
<div class="container">
    <h2 class="title-lg mb">Редактировоание вопроса <%= @question.id%> </h2>
  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <p class="mt">
    <%=link_to "Задати нове питання ", new_question_path, class: "button button-main"%>
  </p>

  <p class="mt">
    <%= render 'form', question: @question %>
  </p>
</div>

<div class="container mt-sm">
  <h2 class="title-lg">
    <%= @questions.count %>
<%= inclination(@questions.count, 'питання', 'питання', 'питань') %>
  </h2>
</div>
  <% @questions.each  do |question| %>
  <div class="mt-sm container">
    <%= render question%>
    </div>
  <%end%>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb"> Нове Питання </h2>
  <!-- форма описана в HTML
  <form action="/questions" method="POST">
  <p><label for= "question[body]">Текст вопроса</label></p>
  <p><textarea name="question[body]" rows=7></textarea></p>
  <p><label for= "question[user_id]">User ID</label></p>
  <p><input type="number" name="questions[user_id]"></p>
  <p><input type="submit" value="Создать"></p>
  </form>
  -->
  <!-- форма описана в Form helper перенесена в паршал _форм -->
  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h1 class="title-lg mb">Вопрос <%= @question.id%> </h1>

  <%= render 'question', question: @question  %>

  <p class="mt"><%=link_to "Все вопросі", questions_path %></p>

</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">присоединяйся и спрашивай!</h2>

<div class="mt">

  <%= form_with model: @user do |form| %>
  <p><%=form.label :name, 'Enter you name' %></p>
  <p><%=form.text_field :name, class: "form-text-field" %></p>

  <p class="mt"><%= form.label :nickname, 'Enter you NickName' %></p>
  <p><%=form.text_field :nickname, class: "form-text-field" %></p>

  <p class="mt"><%= form.label :email %></p>
  <p><%=form.text_field :email, class: "form-text-field" %></p>

  <p class="mt"><%= form.label :password %></p>
  <p><%=form.password_field :password, class: "form-text-field" %></p>

  <p class="mt-lg"><%=form.submit 'Register Now', class: "button button-main"%></p>
  <% end %>
  </div>
</div>